-- Migration 0118 (Fase 2A.1): os templates do playbook deixam de ter campos GENÉRICOS.
--
-- 35 dos 44 templates nasceram com a tríade `["titulo","objetivo","conteudo"]` — um esqueleto que
-- vale para qualquer coisa e por isso não guia coisa nenhuma. Um agente que recebia "produza o
-- template 11 (GMUD)" tinha, como especificação, três palavras que não distinguem uma GMUD de um
-- comunicado de férias. O resultado era prosa plausível sem os fatos que fazem o documento servir:
-- a GMUD sem janela e sem rollback testado, o postmortem sem linha do tempo, o UAT sem critério de
-- aprovação.
--
-- Aqui cada template passa a declarar os campos que ELE exige, derivados do playbook. Duas colunas
-- novas registram o contrato Fixed/Flexible:
--
--   * `metric_formats_json` — para os campos que carregam MÉTRICA, o formato é fixo. "Lead time"
--     escrito ora em horas, ora em dias, ora em "rápido" não é métrica: é opinião com número. Só
--     os templates que têm métrica preenchem; os demais ficam com `{}`.
--   * `guidance` — uma linha dizendo o que o documento precisa provar. Não é prosa de exemplo (que
--     o agente copiaria); é o critério que separa o documento pronto do documento preenchido.
--
-- O que é FIXO: a existência dos campos, a ORDEM em que aparecem e o formato das métricas.
-- O que é LIVRE: a prosa, o vocabulário, o tom e a extensão de cada seção. A regra vale para todos
-- os templates e está enunciada em docs/architecture/workflows/standard-workflow.md.

ALTER TABLE workflow_document_templates ADD COLUMN metric_formats_json TEXT NOT NULL DEFAULT '{}';
ALTER TABLE workflow_document_templates ADD COLUMN guidance TEXT NOT NULL DEFAULT '';

UPDATE workflow_document_templates SET required_fields_json = '["problema_relatado","resultado_esperado","urgencia","solicitante","contexto_conhecido"]', guidance = 'Captura a demanda na linguagem de quem pediu, sem traduzir para termos técnicos: a tradução é trabalho da Triagem e perde informação se acontecer antes.' WHERE code = '00';
UPDATE workflow_document_templates SET required_fields_json = '["valor_negocio","criticidade","decisao_bbir","justificativa","caminho_tecnico"]', guidance = 'Precisa sustentar a decisão Build/Buy/Integrate/Reuse/Reject com o porquê explícito — uma ficha que não permite discordar da decisão não qualificou nada.' WHERE code = '01';
UPDATE workflow_document_templates SET required_fields_json = '["demanda_recusada","motivo","alternativa_oferecida","reavaliacao_possivel"]', guidance = 'Recusar é uma decisão de produto e merece o mesmo rigor de aceitar: quem recebe precisa entender o motivo e saber o que mudaria a resposta.' WHERE code = '02';
UPDATE workflow_document_templates SET required_fields_json = '["objetivo_entrevista","publico","roteiro_perguntas","hipoteses_a_validar","registro_respostas"]', guidance = 'As perguntas existem para derrubar hipóteses, não para confirmá-las; uma hipótese que nenhuma pergunta pode derrubar não é hipótese.' WHERE code = '02b';
UPDATE workflow_document_templates SET required_fields_json = '["problema","publico","objetivos","nao_objetivos","requisitos","nfrs_preliminares","riscos"]', guidance = 'Os NÃO-objetivos valem tanto quanto os objetivos: é a fronteira negativa que impede o escopo de crescer sem decisão.' WHERE code = '03';
UPDATE workflow_document_templates SET required_fields_json = '["como_persona","quero","para_que","criterios_gherkin","invest_check","dependencias"]', guidance = 'Os critérios em Gherkin são a definição de pronto da história — se não dá para escrever o Then, o valor ainda não está claro.' WHERE code = '04';
UPDATE workflow_document_templates SET required_fields_json = '["contexto","decisao","status","alternativas_consideradas","consequencias","consequencias_negativas"]', guidance = 'Registra a decisão E o que ela custa. Um ADR sem consequência negativa não documentou um trade-off — documentou uma preferência.' WHERE code = '05';
UPDATE workflow_document_templates SET required_fields_json = '["visao_ideal","visao_restrita","tradeoffs","aderencia_constraints","evolucao"]', guidance = 'As duas visões são obrigatórias: a ideal mostra para onde a arquitetura quer ir, a restrita mostra o que as restrições de hoje permitem, e a distância entre elas é a dívida que se aceita conscientemente.' WHERE code = '06';
UPDATE workflow_document_templates SET required_fields_json = '["contexto_sistemas_externos","containers","tecnologias_por_container","fluxos_principais","fronteiras_confianca"]', guidance = 'Dois níveis apenas (Contexto e Contêiner). Descer a Componente aqui produz diagrama que envelhece antes do primeiro deploy.' WHERE code = '07';
UPDATE workflow_document_templates SET required_fields_json = '["criterios_avaliacao","opcoes","matriz_comparativa","custo_por_opcao","recomendacao","riscos_da_recomendacao"]', guidance = 'Os critérios vêm ANTES das opções — critério escolhido depois é critério escolhido para justificar a opção que já se queria.' WHERE code = '08';
UPDATE workflow_document_templates SET required_fields_json = '["objetivo_sprint","cards_selecionados","capacidade","dependencias_externas","riscos_do_sprint"]', metric_formats_json = '{"capacidade":"pontos ou cards por sprint, com a unidade declarada"}', guidance = 'A capacidade é medida, não desejada: usar a média realizada das últimas sprints, ou declarar que não há histórico.' WHERE code = '08b';
UPDATE workflow_document_templates SET required_fields_json = '["entidades","relacionamentos","cardinalidades","indices_por_query","volumetria_esperada","politica_retencao"]', metric_formats_json = '{"volumetria_esperada":"linhas por entidade em 12 meses, com a premissa de crescimento declarada"}', guidance = 'Modelar pelas QUERIES reais e pelo crescimento esperado. Um modelo bonito que exige varredura completa na consulta mais frequente está errado.' WHERE code = '09';
UPDATE workflow_document_templates SET required_fields_json = '["escopo_testes","niveis","casos_por_nivel","dados_de_teste","criterios_entrada_saida","ambiente"]', guidance = 'Declara o que NÃO será testado e por quê — cobertura silenciosamente parcial é pior do que cobertura declaradamente parcial.' WHERE code = '09b';
UPDATE workflow_document_templates SET required_fields_json = '["cenarios_gherkin","dados_teste","criterio_aprovacao"]', guidance = 'Escrito para o usuário-chave executar sozinho: qualquer passo que precise de tradução por um técnico invalida o UAT como prova de aceite.' WHERE code = '10';
UPDATE workflow_document_templates SET required_fields_json = '["ativos","superficie_ataque","ameacas_stride","controles","riscos_residuais","owasp_2025"]', guidance = 'Nomeia o risco residual aceito e quem aceitou. Threat model sem risco residual ou é incompleto ou é ficção.' WHERE code = '10b';
UPDATE workflow_document_templates SET required_fields_json = '["janela","plano_execucao","plano_rollback_testado","criterios_saude","aprovador"]', metric_formats_json = '{"janela":"início e fim em ISO-8601 com fuso","criterios_saude":"métrica, limiar e janela de observação"}', guidance = 'O rollback precisa ter sido EXECUTADO em ensaio, não apenas escrito. Plano de rollback não testado é plano de esperança.' WHERE code = '11';
UPDATE workflow_document_templates SET required_fields_json = '["slis","slos","alertas","dashboards","instrumentacao_por_servico","retencao"]', metric_formats_json = '{"slos":"objetivo percentual e janela (ex.: 99,9% em 30 dias)","slis":"numerador/denominador explícitos"}', guidance = 'Cada SLO precisa de um SLI que alguém consiga calcular hoje — objetivo sem indicador mensurável é slogan.' WHERE code = '11b';
UPDATE workflow_document_templates SET required_fields_json = '["dor_criterios","dod_criterios","excecoes","responsavel_verificacao"]', guidance = 'Critérios verificáveis por terceiro. "Bem testado" não é critério; "cobertura da suíte verde no CI" é.' WHERE code = '12';
UPDATE workflow_document_templates SET required_fields_json = '["escopo_operacao","procedimentos","comandos","diagnostico_por_sintoma","escalonamento","contatos"]', guidance = 'Escrito para quem for chamado às três da manhã sem contexto: cada procedimento começa pelo sintoma observável, não pelo nome interno do componente.' WHERE code = '12b';
UPDATE workflow_document_templates SET required_fields_json = '["releases","escopo_por_release","datas_alvo","dependencias","marcos"]', metric_formats_json = '{"datas_alvo":"data ISO-8601; intervalo quando houver incerteza declarada"}', guidance = 'Data com incerteza declarada vale mais que data falsamente precisa.' WHERE code = '13';
UPDATE workflow_document_templates SET required_fields_json = '["linha_tempo","causa_raiz","fatores","acoes","donos","prazos"]', metric_formats_json = '{"linha_tempo":"timestamps ISO-8601 com fuso, do primeiro sintoma à normalização"}', guidance = 'Blameless: descreve sistema e decisões sob a informação disponível NA HORA, nunca pessoas. Toda ação tem dono e prazo, ou não é ação.' WHERE code = '13b';
UPDATE workflow_document_templates SET required_fields_json = '["riscos","probabilidade_impacto","mitigacoes","dependencias_externas","gatilhos_de_revisao"]', metric_formats_json = '{"probabilidade_impacto":"escala 1-5 para cada eixo, com o critério de cada nível declarado"}', guidance = 'Risco sem gatilho de revisão é risco esquecido: declara o evento que obriga a reavaliar.' WHERE code = '14';
UPDATE workflow_document_templates SET required_fields_json = '["escopo_revisado","achados_por_severidade","aderencia_arquitetural","testes_verificados","veredito","justificativa_veredito"]', guidance = 'Revisor DIFERENTE do implementador. O veredito nomeia a camada que falhou e a severidade — "precisa melhorar" não é veredito.' WHERE code = '15';
UPDATE workflow_document_templates SET required_fields_json = '["lead_time","deploy_frequency","change_failure_rate","mttr","periodo_medido","fonte_dos_dados"]', metric_formats_json = '{"lead_time":"duração ISO-8601 (P50 e P90)","deploy_frequency":"contagem por período declarado","change_failure_rate":"percentual sobre total de mudanças","mttr":"duração ISO-8601 (mediana)"}', guidance = 'As quatro métricas saem do ledger, não de estimativa. Sem fonte rastreável, o número não entra.' WHERE code = '16';
UPDATE workflow_document_templates SET required_fields_json = '["termos","definicao_por_termo","sinonimos_proibidos","contexto_delimitado"]', guidance = 'Um termo, uma definição. Sinônimo aceito é ambiguidade que reaparece como bug de interpretação.' WHERE code = '17';
UPDATE workflow_document_templates SET required_fields_json = '["objetivo_do_card","contexto_minimo","arquivos_provaveis","criterios_aceite","restricoes","evidencia_esperada"]', guidance = 'É o que o executor recebe. Se o briefing não permite começar sem perguntar, ele ainda não está pronto.' WHERE code = '18';
UPDATE workflow_document_templates SET required_fields_json = '["sintoma","impacto","investigacao","causa","correcao","prevencao"]', guidance = 'Separa causa de sintoma. Correção que trata o sintoma é registrada como tal, para não ser confundida com prevenção.' WHERE code = '19';
UPDATE workflow_document_templates SET required_fields_json = '["gates_avaliados","resultado_por_gate","defeitos_abertos_por_severidade","cobertura","veredito"]', metric_formats_json = '{"cobertura":"percentual por tipo de teste, com a ferramenta declarada"}', guidance = 'Default-FAIL: gate não executado conta como reprovado, nunca como neutro.' WHERE code = '20';
UPDATE workflow_document_templates SET required_fields_json = '["cenarios_carga","metricas_observadas","limiares","gargalos","recomendacoes"]', metric_formats_json = '{"metricas_observadas":"latência P50/P95/P99 em ms, throughput em req/s, erro em percentual"}', guidance = 'Sem percentis não há relatório de performance — a média esconde exatamente a cauda que derruba o usuário.' WHERE code = '21';
UPDATE workflow_document_templates SET required_fields_json = '["escopo_testado","metodologia","vulnerabilidades_por_severidade","evidencias","correcoes_recomendadas","reteste"]', guidance = 'Cada vulnerabilidade com evidência reproduzível e caminho de correção. Achado sem reprodução não é achado, é suspeita.' WHERE code = '22';
UPDATE workflow_document_templates SET required_fields_json = '["criterios_go","situacao_por_criterio","riscos_residuais","decisao","condicoes_da_decisao"]', guidance = 'No-Go também é resultado válido e não é fracasso. Go condicional declara a condição e quem a verifica.' WHERE code = '23';
UPDATE workflow_document_templates SET required_fields_json = '["cenarios_executados","resultado_por_cenario","defeitos_encontrados","evidencias","conclusao"]', guidance = 'Resultado por cenário, não agregado: "18 de 20 passaram" esconde quais dois falharam e o que eles significam.' WHERE code = '24';
UPDATE workflow_document_templates SET required_fields_json = '["escopo_aceito","criterios_atendidos","ressalvas","aprovador_humano","data_aceite"]', metric_formats_json = '{"data_aceite":"data e hora ISO-8601 com fuso"}', guidance = 'Gate HUMANO. Silêncio nunca é aprovação: sem aprovador nomeado e data, não há aceite.' WHERE code = '25';
UPDATE workflow_document_templates SET required_fields_json = '["defeitos","severidade","passos_reproducao","impacto_no_aceite","tratamento"]', guidance = 'Separa o que bloqueia o aceite do que vira backlog — misturar os dois transforma UAT em negociação.' WHERE code = '26';
UPDATE workflow_document_templates SET required_fields_json = '["versao","novidades","correcoes","mudancas_incompativeis","instrucoes_atualizacao"]', guidance = 'Escrito para quem USA, não para quem desenvolveu. Mudança incompatível vem primeiro e em destaque.' WHERE code = '27';
UPDATE workflow_document_templates SET required_fields_json = '["gatilhos_de_rollback","procedimento","tempo_estimado","impacto_dados","validacao_pos_rollback","ensaio_realizado"]', metric_formats_json = '{"tempo_estimado":"duração ISO-8601 medida no ensaio"}', guidance = 'O gatilho é objetivo e observável, para que a decisão de reverter não dependa de julgamento no meio da crise.' WHERE code = '28';
UPDATE workflow_document_templates SET required_fields_json = '["componentes","versoes","licencas","origem","vulnerabilidades_conhecidas"]', guidance = 'Inventário completo do que foi de fato empacotado, gerado da build — SBOM escrito à mão descreve o que se acredita ter empacotado.' WHERE code = '29';
UPDATE workflow_document_templates SET required_fields_json = '["periodo","disponibilidade","incidentes","chamados_por_categoria","sla_cumprido","acoes_do_periodo"]', metric_formats_json = '{"disponibilidade":"percentual no período, com a janela declarada","sla_cumprido":"percentual de chamados dentro do prazo, por severidade"}', guidance = 'Relatório de operação é prestação de contas: número fora do SLA aparece com a causa e a ação, não diluído no agregado.' WHERE code = '30';
UPDATE workflow_document_templates SET required_fields_json = '["demanda_atual","projecao","limites_atuais","pontos_de_saturacao","plano_de_expansao"]', metric_formats_json = '{"projecao":"horizonte em meses com a premissa de crescimento declarada","pontos_de_saturacao":"recurso, limiar e métrica observável"}', guidance = 'A projeção declara sua premissa. Extrapolação sem premissa explícita não é planejamento, é torcida.' WHERE code = '31';
UPDATE workflow_document_templates SET required_fields_json = '["cenario_exercitado","hipoteses","execucao","comportamento_observado","lacunas","acoes"]', guidance = 'Game day existe para descobrir a lacuna antes do incidente real. Exercício que não encontrou nada precisa questionar o cenário, não comemorar.' WHERE code = '32';
UPDATE workflow_document_templates SET required_fields_json = '["cenario_desastre","rto_alvo","rpo_alvo","rto_medido","rpo_medido","lacunas","acoes"]', metric_formats_json = '{"rto_alvo":"duração ISO-8601","rpo_alvo":"duração ISO-8601","rto_medido":"duração ISO-8601 cronometrada no exercício","rpo_medido":"duração ISO-8601 verificada nos dados restaurados"}', guidance = 'Alvo e MEDIDO lado a lado. O valor do exercício está na distância entre os dois.' WHERE code = '33';
UPDATE workflow_document_templates SET required_fields_json = '["o_que_foi_entregue","como_acessar","proximos_passos","onde_pedir_ajuda"]', guidance = 'Para o dono, em linguagem de negócio: sem termo técnico, sem nome de componente, sem jargão de processo interno.' WHERE code = '34';
UPDATE workflow_document_templates SET required_fields_json = '["personas","jornadas","atividades","historias_por_atividade","fatiamento_de_releases"]', guidance = 'O mapa mostra a jornada inteira antes do recorte; fatiar sem ver o todo produz release que não completa nenhum caminho do usuário.' WHERE code = '34b';
UPDATE workflow_document_templates SET required_fields_json = '["situacao_atual","o_que_muda_para_voce","quando","o_que_fazer","onde_pedir_ajuda"]', guidance = 'Para o dono, em linguagem de negócio, com a ação esperada dele em destaque — comunicado que não diz o que fazer é ruído.' WHERE code = '35';
UPDATE workflow_document_templates SET required_fields_json = '["desempenho","disponibilidade","seguranca","escalabilidade","observabilidade","restricoes_conhecidas"]', metric_formats_json = '{"desempenho":"latência alvo em ms por percentil","disponibilidade":"percentual e janela (ex.: 99,5% mensal)"}', guidance = 'Preliminar não é vago: cada NFR nasce com número ou com a declaração explícita de que ainda não há número e de quem vai defini-lo.' WHERE code = '35b';
UPDATE workflow_document_templates SET guidance = 'Card de história: o "para" carrega o valor, e é ele que decide se a história ainda vale quando o escopo apertar.' WHERE code = '36';
UPDATE workflow_document_templates SET guidance = 'Card leve: a validação objetiva é o que separa a tarefa concluída da tarefa abandonada — sem ela não há como fechar o card sem opinião.' WHERE code = '37';
