<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Harness.Persistence.Abstractions/Harness.Persistence.Abstractions.csproj" />
    <ProjectReference Include="../Harness.Persistence.Sqlite/Harness.Persistence.Sqlite.csproj" />
    <ProjectReference Include="../Harness.Persistence.Postgres/Harness.Persistence.Postgres.csproj" />
  </ItemGroup>

</Project>
