namespace Harness.Host.Realtime;

public static class EventTypeCatalog
{
    public static IReadOnlySet<string> All { get; } = new SortedSet<string>(StringComparer.Ordinal)
    {
        "agent.statusChanged",
        "agentRun.stateChanged",
        "approval.requested",
        "approval.resolved",
        "attempt.completed",
        "attempt.failed",
        "attempt.heartbeat",
        "attempt.started",
        "audit.eventAppended",
        "chat.turnChunk",
        "chat.turnCompleted",
        "chat.turnStarted",
        "chief.turnStateChanged",
        "decision.requested",
        "decision.resolved",
        "demand.created",
        "document.stateChanged",
        "execution.blocked",
        "execution.enqueued",
        "gate.changed",
        "message.appended",
        "message.received",
        "model.responded",
        "notification.created",
        "progress.updated",
        "project.created",
        "prototype.created",
        "prototype.stateChanged",
        "provider.invoked",
        "quota.updated",
        "readiness.changed",
        "run.logAppended",
        "task.created",
        "task.stateChanged",
        "tool.statusChanged",
        "turn.registered",
        "workflow.versionPublished",
    };
}
