import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errs = [];
page.on('console', m => { if (m.type()==='error') errs.push(m.text().slice(0,160)); });
page.on('pageerror', e => errs.push('PAGEERROR: '+String(e).slice(0,160)));
const failed = [];
page.on('response', r => { if (r.status()>=400) failed.push(r.status()+' '+r.url().replace('http://127.0.0.1:5173','')); });
await page.goto('http://127.0.0.1:5173/delivery', { waitUntil:'networkidle' });
await page.waitForTimeout(2500);
console.log('URL final:', page.url());
console.log('TITULO  :', await page.title());
console.log('H1/H2   :', (await page.locator('h1,h2').allTextContents()).slice(0,6).join(' | '));
console.log('dl/dt/dd:', await page.locator('dl').count(), await page.locator('dt').count(), await page.locator('dd').count());
console.log('TEXTO   :', (await page.locator('body').innerText()).replace(/\n+/g,' ⏎ ').slice(0,400));
console.log('ERROS CONSOLE:', errs.length ? errs.slice(0,5) : 'nenhum');
console.log('HTTP >=400  :', failed.length ? [...new Set(failed)].slice(0,8) : 'nenhum');
await browser.close();
